[tools]
python = { version = "3.12", postinstall = "python3 -m pip install --upgrade pip" }
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[settings]
python.uv_venv_auto = "create|source"

[task.setup]
run = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -e .",
]
