apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    type: local
  name: homarr-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/kubernetes-pv/homarr
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
