apiVersion: v1
kind: Namespace
metadata:
  name: testing-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: testing-pod
  namespace: testing-namespace
spec:
  containers:
  - image: alpine
    name: alpine-pod
    volumeMounts:
      - name: some-storage
        mountPath: "/data"
    command: ["sleep"]
    args: ["infinite"]
  volumes:
    - name: some-storage
      persistentVolumeClaim:
        claimName: required-pvc
---
# remember, cannot be namespaced. PVC are namespaced PV doesnt.
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    type: local
  name: required
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /opt/kubernetes-storage/test
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: required-pvc
  namespace: testing-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1000Mi
  volumeName: required
