apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-sample
  name: nginx-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: scratch-vol
            mountPath: "/scr_directory"
      volumes:
      - name: scratch-vol
        emptyDir:
          sizeLimit: 500Mi
