apiVersion: v1
kind: Namespace
metadata:
  name: homarr
---
apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homarr
type: Opaque
data:
  db-encryption-key: N2JlYWI4ZjM2MTA2OGU3YzBjODUzODQzYzNkMTVkYmJjZGFiNGM2MjZiNDNiNDljNDUzYzVmYjUwNTJlYWI5Nw==
