#k create secret generic db-encryption --dry-run=client --from-literal=db-encryption=$(openssl rand -hex 32) --namespace any -o yaml > test-secret.yaml

apiVersion: v1
data:
  db-encryption: REDACTED 
kind: Secret
metadata:
  name: db-encryption (works like selector in a way)
  namespace: (keep namespaced)
