apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: mealie-pv
  resources:
    requests:
      storage: 600Mi
