apiVersion: v1
kind: Service
metadata:
  name: mealie-loadbalancer
  namespace: mealie
  labels:
    app: mealie
spec:
  ports:
    # -- port to service --
    - port: 8001
      protocol: TCP
    # -- port to container --
      targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer

