#!/usr/bin/bash

get_time() {
	time="$(date +%H:%M)"
	minutes=$((10#${time#*:}))
	hours=$((10#${time%:*}))
	
	echo "$minutes"
	echo "$hours"
	echo "$time"
}

# Extract variables from function
mapfile -t result < <(get_time)
minutes="${result[0]}"
hours="${result[1]}"
time="${result[2]}"

# Calculate lesson end time
hours_end=$hours
min_end=$(( minutes + 50 ))

if [[ $min_end -ge 60 ]]; then
	min_end_over=$(( min_end - 60 ))
	hours_end=$(( hours + 1 ))
else
	min_end_over=$min_end
fi

# Add leading zero for single-digit minutes (e.g., 05 instead of 5)
printf -v min_end_formatted "%02d" "$min_end_over"

lesson_end="${hours_end}:${min_end_formatted}"

echo "Lesson start time: ${time}"
echo "Lesson end time: ${lesson_end}"

is_running=1
while [[ "${is_running}" != "0" ]]; do 
	mapfile -t result < <(get_time)
	minutes="${result[0]}"
	hours="${result[1]}"
			
	if [[ $hours -ge ${hours_end} && ${minutes} -ge ${min_end_over} ]]; then
		is_running="0"
	fi	
	sleep 30
done

echo "Lesson finished!"
