#!/usr/bin/bash

time="$(date +%H:%M)"
minutes=${time#*:}
hours=${time%:*}

echo "Timer start: ${time}"

# koniec lekcji 
min_end=$(( ${minutes} + 50 ))
if [[ min_end -ge 60 ]];then
	min_end_over=$((  min_end - 60 ))
	hours=$(( ${hours} + 1 ))
fi 
echo "Timer stop: ${hours}:${min_end_over}"
koniec_lekcji="${hours}:${min_end_over}"
